### ISSUE TITLE
Properties\AssemblyInfo.cs went missing

### ISSUE THREAD

**Issue by codespare** [mjsabby/ClangSharp#1]
In commit 7ae9c88fc91d0c7e4444e78dc19ce93061783bf9

**Comment by mjsabby** [comment]
It is also removed from the CSProj. Is there any reason you need it?

**Comment by codespare** [comment]
ClangSharp.csproj on master still has:
    <Compile Include="Properties\AssemblyInfo.cs" />
Line 43 when browsed through github,
I kept building via the original projs after you introduced the build.bat because I find it's easier to control the target platform that way. But I understand that's Windows only.

**Comment by mjsabby** [comment]
Thanks @codespare. Fixed in https://github.com/mjsabby/ClangSharp/commit/42fb52a22cc7ba7820ab02bb95edaba9e7320661
