### ISSUE TITLE
How do you successfully run the "command line tests" for a clang you build yourself?

### ISSUE THREAD

**Issue by david-bakin** [mjsabby/ClangSharp#4]
I have tried building clang/llvm myself using the documented process that uses CMake to generate Visual Studio 2013 (win64) solution and project files.  I build fine (no errors) and all unit tests pass.

However, if I then attempt to run the [command line tests] (http://clang.llvm.org/hacking.html#testingCommands) I have ~150 "unexpected failures", all due to some kind of lock file problem.

Are these tests supposed to be able to be run on the Windows/Visual Studio platform?  If so, is there anything undocumented I need to do to get them to run?

(I'm afraid my home-built clang/llvm isn't working properly ... and I'd rather discover sooner than later.)

Thanks! -- David

**Comment by mjsabby** [comment]
Sorry I'm not sure. cfe-dev@lists.cs.uiuc.edu would be your best bet.

**Comment by david-bakin** [comment]
ok.
