### ISSUE TITLE
Crash on invoking parseTranslationUnit function.

### ISSUE THREAD

**Issue by venkatmakam** [mjsabby/ClangSharp#5]
When i invoke parseTranslationUnit with the following scenario i am getting crash.
string[] args2 = new string[2];
            args2[0] = "-include-pch";
            args2[1] = "testfiles.h.pch";
            nargs = 2;
            CXTranslationUnit translationUnit;
            ClangSharp.clang.
            parseTranslationUnit(m_ClangIndex, "DummyFile.cpp", args2, 0, out unsavedFiles[0], 1, (uint)ClangSharp.CXTranslationUnit_Flags.CXTranslationUnit_ForSerialization);

The same call is working when i invoke from c++.

**Comment by mjsabby** [comment]
Can you share the dummy file code? I can't reproduce the error.

**Comment by mjsabby** [comment]
No comments, so I'm assuming you've found a workaround or the issue is fixed.
