### ISSUE TITLE
Move ClangSharpPInvokeGenerator to separate repo.

### ISSUE THREAD

**Issue by KvanTTT** [mjsabby/ClangSharp#6]
I like the idea of ClangSharpPInvokeGenerator. It is very usefull for native dll .NET wrapper generation.
I suppose to move it to separate repo for further development (UI, improvements).

**Comment by mjsabby** [comment]
Yes, this is a good idea. I've created a repo https://github.com/ClangSharp/PInvokeGenerator. If you want, I can add you as a organization member and you can do all the sweet things you're talking about :)

**Comment by KvanTTT** [comment]
Ok, thank you, please add me :)

**Comment by mjsabby** [comment]
Done
