### ISSUE TITLE
Support for compilation database

### ISSUE THREAD

**Issue by ajithpadman** [mjsabby/ClangSharp#8]
Do you have support for the Jason compilation database? If not any plans of adding the same?

**Comment by ajithpadman** [comment]
sorry I misunderstood something. I generated the interfaces for compilation database :) thanks

**Comment by mjsabby** [comment]
I don't follow, what is missing that needs to be added?

**Comment by ajithpadman** [comment]
it was a mistake in my understanding... You can close this issue.

**Comment by mjsabby** [comment]
Ok.
